# Site
title: CHILBERTCO
description: Adventure. Risk. Coffee.
url: http://chilbert.co
logo:   logo.png  # Site logo
locale: en_US
excerpt_separator: <!-- more -->
host: localhost

assets:
  compress:
    css: false
    js: false

# Left Block Images
background:
  home: assets/images/home.png            # this image will be shown on homepage's left block
  post: assets/images/unsplash-image-4.jpg            # this image will be shown when post's front matter doesn't specify any image
  post-list: assets/images/unsplash-image-6.jpg  # this image will be shown on post list page

# Jekyll
permalink: /:categories/:year/:month/:day/:title
future: true
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
  input:            GFM
sass:
  # style:            compressed

# Google Analytics
#google-analytics: UA-XXXXX-Y

# Social Links
email:              chase@chilbert.co
twitter:            chilbert
facebook:          chase.hilbert
github:             chilbert
linkedin:          chasehilbert
instagram:          chilbert
strava:            athletes/1379129


# Gems
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]
